flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- ghc-boot-th-8.0.1
- haskell-src-exts-1.18.2
- haskell-src-exts-prisms-1.18.2.0
- kan-extensions-5.0.1
- lens-4.14
- simple-zipper-0.1.0.0
- template-haskell-2.11.0.0
resolver: lts-6.10
