flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HUnit-1.3.1.1
- QuickCheck-2.9.1
- StateVar-1.1.0.4
- adjunctions-4.3
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.1.0
- attoparsec-0.13.1.0
- base-orphans-0.5.4
- bifunctors-5.4.1
- blaze-builder-0.4.0.2
- blaze-html-0.9.0.1
- blaze-markup-0.8.0.0
- charset-0.3.7.1
- comonad-5
- contravariant-1.4
- cpphs-1.20.1
- data-default-0.7.1.1
- data-default-class-0.1.2.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- distributive-0.5.0.2
- dlist-0.8.0.1
- exceptions-0.8.3
- fingertree-0.1.1.0
- free-4.12.4
- hashable-1.2.4.0
- haskell-src-exts-1.18.2
- haskell-src-exts-prisms-1.18.2.0
- hspec-2.2.3
- hspec-core-2.2.3
- hspec-discover-2.2.3
- hspec-expectations-0.7.2
- integer-logarithms-1.0.1
- kan-extensions-5.0.1
- lens-4.14
- microlens-0.4.6.0
- microlens-mtl-0.1.10.0
- microlens-th-0.4.0.0
- mtl-2.2.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parallel-3.2.1.0
- parsec-3.1.11
- parsers-0.12.4
- polyparse-1.12
- prelude-extras-0.4.0.3
- primitive-0.6.1.0
- profunctors-5.2
- quickcheck-io-0.1.3
- random-1.1
- reducers-3.12.1
- reflection-2.1.2
- scientific-0.3.4.10
- semigroupoids-5.1
- semigroups-0.18.2
- setenv-0.1.1.3
- simple-zipper-0.1.0.0
- stm-2.4.4.1
- tagged-0.8.5
- text-1.2.2.1
- tf-random-0.5
- transformers-compat-0.5.1.4
- trifecta-1.6.2.1
- unordered-containers-0.2.7.1
- utf8-string-1.0.1.1
- vector-0.11.0.0
- void-0.7.1
- vty-5.7.1
resolver: ghc-8.0.1
